version: '3'

services:
  postgres-vehicle-manager:
    image: postgres:16-alpine3.18
    container_name: postgres-vehicle-manager
    restart: on-failure
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres-vehicle-manager:/data/postgres-vehicle-manager

volumes:
    postgres-vehicle-manager: