postgres:
  host: localhost
  port: 5432
  database: nuvoroute

spring:
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:postgresql://${postgres.host}:${postgres.port}/${postgres.database}
    username: admin
